-- 조건에 부합하는 중고거래 댓글 조회하기
-- %y 두자리 연도, %Y 네자리 연도
SELECT TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B 
WHERE A.BOARD_ID = B.BOARD_ID AND YEAR(A.CREATED_DATE) = 2022 AND MONTH(A.CREATED_DATE) = 10 
ORDER BY B.CREATED_DATE ASC, TITLE ASC;