-- 부모의 형질(GENOTYPE)을 모두 보유한 대장균의 ID, GENOTYPE, PARENT_GENOTYPE
-- ID 순서대로 오름차순 정렬
-- 

SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C 
JOIN ECOLI_DATA P ON C.PARENT_ID = P.ID 
WHERE C.GENOTYPE & P.GENOTYPE = P.GENOTYPE 
ORDER BY C.ID;