-- 코드를 작성해주세요
SELECT PARENT.ITEM_ID, PARENT.ITEM_NAME, PARENT.RARITY 
FROM ITEM_INFO CHILD
JOIN ITEM_TREE TREE ON CHILD.ITEM_ID = TREE.PARENT_ITEM_ID
JOIN ITEM_INFO PARENT ON TREE.ITEM_ID = PARENT.ITEM_ID
WHERE CHILD.RARITY = 'RARE'
ORDER BY PARENT.ITEM_ID DESC;