-- 코드를 작성해주세요
-- 연도별로 가장 큰 대장균의 크기를 구하고, 연도가 같은 것들에서 각 대장균의 크기를 제한다.
SELECT B.YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY YEAR_DEV, ID FROM ECOLI_DATA A JOIN (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR ORDER BY YEAR, YEAR_DEV