-- 12세 이하인 여자 환자 목록 출력하기
-- Null일 때 다른 것으로 출력하는 것은 COALESCE, IFNULL, CASE WHEN 등이 있음
SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(A.TLNO, 'NONE') AS TLNO
FROM PATIENT AS A
WHERE A.GEND_CD LIKE 'W' AND A.AGE <= 12
ORDER BY AGE DESC, PT_NAME ASC;

SELECT PT_NAME, PT_NO, GEND_CD, AGE,
    CASE 
        WHEN A.TLNO IS NULL THEN 'NONE'
        ELSE A.TLNO
    END AS TLNO
FROM PATIENT AS A
WHERE A.GEND_CD LIKE 'W' AND A.AGE <= 12
ORDER BY AGE DESC, PT_NAME ASC;