-- 과일로 만든 아이스크림 고르기
-- Inner join을 통해 두 테이블을 연결해준 후 조건에 맞게 찾아서 정렬하기
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
INNER JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE ICECREAM_INFO.INGREDIENT_TYPE LIKE 'fruit_based' AND FIRST_HALF.TOTAL_ORDER > 3000
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;