
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT P.ITEM_ID
                  FROM ITEM_INFO AS I, ITEM_TREE AS P
                 WHERE I.ITEM_ID = P.PARENT_ITEM_ID AND I.RARITY = "RARE")
ORDER BY ITEM_ID DESC;